# FIXED
6_TempCtrl_ARL/tem_control.obj: ../6_TempCtrl_ARL/tem_control.c
6_TempCtrl_ARL/tem_control.obj: ../6_TempCtrl_ARL/PWM_tem.h
6_TempCtrl_ARL/tem_control.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/3_NEW_Data_Process/INCLUDE/DSP2833x_Device.h
6_TempCtrl_ARL/tem_control.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/3_NEW_Data_Process/INCLUDE/DSP2833x_Adc.h
6_TempCtrl_ARL/tem_control.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/3_NEW_Data_Process/INCLUDE/DSP2833x_DevEmu.h
6_TempCtrl_ARL/tem_control.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/3_NEW_Data_Process/INCLUDE/DSP2833x_CpuTimers.h
6_TempCtrl_ARL/tem_control.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/3_NEW_Data_Process/INCLUDE/DSP2833x_ECan.h
6_TempCtrl_ARL/tem_control.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/3_NEW_Data_Process/INCLUDE/DSP2833x_ECap.h
6_TempCtrl_ARL/tem_control.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/3_NEW_Data_Process/INCLUDE/DSP2833x_DMA.h
6_TempCtrl_ARL/tem_control.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/3_NEW_Data_Process/INCLUDE/DSP2833x_EPwm.h
6_TempCtrl_ARL/tem_control.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/3_NEW_Data_Process/INCLUDE/DSP2833x_EQep.h
6_TempCtrl_ARL/tem_control.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/3_NEW_Data_Process/INCLUDE/DSP2833x_Gpio.h
6_TempCtrl_ARL/tem_control.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/3_NEW_Data_Process/INCLUDE/DSP2833x_I2c.h
6_TempCtrl_ARL/tem_control.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/3_NEW_Data_Process/INCLUDE/DSP2833x_McBSP.h
6_TempCtrl_ARL/tem_control.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/3_NEW_Data_Process/INCLUDE/DSP2833x_PieCtrl.h
6_TempCtrl_ARL/tem_control.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/3_NEW_Data_Process/INCLUDE/DSP2833x_PieVect.h
6_TempCtrl_ARL/tem_control.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/3_NEW_Data_Process/INCLUDE/DSP2833x_Spi.h
6_TempCtrl_ARL/tem_control.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/3_NEW_Data_Process/INCLUDE/DSP2833x_Sci.h
6_TempCtrl_ARL/tem_control.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/3_NEW_Data_Process/INCLUDE/DSP2833x_SysCtrl.h
6_TempCtrl_ARL/tem_control.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/3_NEW_Data_Process/INCLUDE/DSP2833x_XIntrupt.h
6_TempCtrl_ARL/tem_control.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/3_NEW_Data_Process/INCLUDE/DSP2833x_Xintf.h
6_TempCtrl_ARL/tem_control.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/3_NEW_Data_Process/INCLUDE/DSP2833x_Examples.h
6_TempCtrl_ARL/tem_control.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/3_NEW_Data_Process/INCLUDE/DSP2833x_GlobalPrototypes.h
6_TempCtrl_ARL/tem_control.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/3_NEW_Data_Process/INCLUDE/DSP2833x_ePwm_defines.h
6_TempCtrl_ARL/tem_control.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/3_NEW_Data_Process/INCLUDE/DSP2833x_Dma_defines.h
6_TempCtrl_ARL/tem_control.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/3_NEW_Data_Process/INCLUDE/DSP2833x_I2C_defines.h
6_TempCtrl_ARL/tem_control.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/3_NEW_Data_Process/INCLUDE/DSP2833x_DefaultISR.h
6_TempCtrl_ARL/tem_control.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/3_NEW_Data_Process/A_MAIN/std_init.h
6_TempCtrl_ARL/tem_control.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/3_NEW_Data_Process/4_DataPro_ARL/ConstData_Table.h
6_TempCtrl_ARL/tem_control.obj: ../6_TempCtrl_ARL/tem_control.h
