# FIXED
7_FTF_ARL/hmi_driver.obj: ../7_FTF_ARL/hmi_driver.c
7_FTF_ARL/hmi_driver.obj: ../7_FTF_ARL/hmi_driver.h
7_FTF_ARL/hmi_driver.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/3_SCI_ARL/hmi_user_uart.h
7_FTF_ARL/hmi_driver.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_Device.h
7_FTF_ARL/hmi_driver.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_Adc.h
7_FTF_ARL/hmi_driver.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_DevEmu.h
7_FTF_ARL/hmi_driver.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_CpuTimers.h
7_FTF_ARL/hmi_driver.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_ECan.h
7_FTF_ARL/hmi_driver.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_ECap.h
7_FTF_ARL/hmi_driver.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_DMA.h
7_FTF_ARL/hmi_driver.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_EPwm.h
7_FTF_ARL/hmi_driver.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_EQep.h
7_FTF_ARL/hmi_driver.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_Gpio.h
7_FTF_ARL/hmi_driver.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_I2c.h
7_FTF_ARL/hmi_driver.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_McBSP.h
7_FTF_ARL/hmi_driver.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_PieCtrl.h
7_FTF_ARL/hmi_driver.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_PieVect.h
7_FTF_ARL/hmi_driver.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_Spi.h
7_FTF_ARL/hmi_driver.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_Sci.h
7_FTF_ARL/hmi_driver.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_SysCtrl.h
7_FTF_ARL/hmi_driver.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_XIntrupt.h
7_FTF_ARL/hmi_driver.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_Xintf.h
7_FTF_ARL/hmi_driver.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_Examples.h
7_FTF_ARL/hmi_driver.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_GlobalPrototypes.h
7_FTF_ARL/hmi_driver.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_ePwm_defines.h
7_FTF_ARL/hmi_driver.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_Dma_defines.h
7_FTF_ARL/hmi_driver.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_I2C_defines.h
7_FTF_ARL/hmi_driver.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_DefaultISR.h
7_FTF_ARL/hmi_driver.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/A_MAIN/std_init.h
7_FTF_ARL/hmi_driver.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/4_DataPro_ARL/ConstData_Table.h
