# FIXED
ARL/hmi_driver.obj: ../ARL/hmi_driver.c
ARL/hmi_driver.obj: ../ARL/hmi_driver.h
ARL/hmi_driver.obj: ../ARL/hmi_user_uart.h
ARL/hmi_driver.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/Uart_TFT_test/INCLUDE/DSP2833x_Device.h
ARL/hmi_driver.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/Uart_TFT_test/INCLUDE/DSP2833x_Adc.h
ARL/hmi_driver.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/Uart_TFT_test/INCLUDE/DSP2833x_DevEmu.h
ARL/hmi_driver.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/Uart_TFT_test/INCLUDE/DSP2833x_CpuTimers.h
ARL/hmi_driver.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/Uart_TFT_test/INCLUDE/DSP2833x_ECan.h
ARL/hmi_driver.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/Uart_TFT_test/INCLUDE/DSP2833x_ECap.h
ARL/hmi_driver.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/Uart_TFT_test/INCLUDE/DSP2833x_DMA.h
ARL/hmi_driver.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/Uart_TFT_test/INCLUDE/DSP2833x_EPwm.h
ARL/hmi_driver.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/Uart_TFT_test/INCLUDE/DSP2833x_EQep.h
ARL/hmi_driver.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/Uart_TFT_test/INCLUDE/DSP2833x_Gpio.h
ARL/hmi_driver.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/Uart_TFT_test/INCLUDE/DSP2833x_I2c.h
ARL/hmi_driver.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/Uart_TFT_test/INCLUDE/DSP2833x_McBSP.h
ARL/hmi_driver.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/Uart_TFT_test/INCLUDE/DSP2833x_PieCtrl.h
ARL/hmi_driver.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/Uart_TFT_test/INCLUDE/DSP2833x_PieVect.h
ARL/hmi_driver.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/Uart_TFT_test/INCLUDE/DSP2833x_Spi.h
ARL/hmi_driver.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/Uart_TFT_test/INCLUDE/DSP2833x_Sci.h
ARL/hmi_driver.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/Uart_TFT_test/INCLUDE/DSP2833x_SysCtrl.h
ARL/hmi_driver.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/Uart_TFT_test/INCLUDE/DSP2833x_XIntrupt.h
ARL/hmi_driver.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/Uart_TFT_test/INCLUDE/DSP2833x_Xintf.h
ARL/hmi_driver.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/Uart_TFT_test/INCLUDE/DSP2833x_Examples.h
ARL/hmi_driver.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/Uart_TFT_test/INCLUDE/DSP2833x_GlobalPrototypes.h
ARL/hmi_driver.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/Uart_TFT_test/INCLUDE/DSP2833x_ePwm_defines.h
ARL/hmi_driver.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/Uart_TFT_test/INCLUDE/DSP2833x_Dma_defines.h
ARL/hmi_driver.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/Uart_TFT_test/INCLUDE/DSP2833x_I2C_defines.h
ARL/hmi_driver.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/Uart_TFT_test/INCLUDE/DSP2833x_DefaultISR.h
