# FIXED
MAIN/mian.obj: ../MAIN/mian.c
MAIN/mian.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/LED_sample_test/INCLUDE/DSP2833x_Device.h
MAIN/mian.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/LED_sample_test/INCLUDE/DSP2833x_Adc.h
MAIN/mian.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/LED_sample_test/INCLUDE/DSP2833x_DevEmu.h
MAIN/mian.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/LED_sample_test/INCLUDE/DSP2833x_CpuTimers.h
MAIN/mian.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/LED_sample_test/INCLUDE/DSP2833x_ECan.h
MAIN/mian.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/LED_sample_test/INCLUDE/DSP2833x_ECap.h
MAIN/mian.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/LED_sample_test/INCLUDE/DSP2833x_DMA.h
MAIN/mian.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/LED_sample_test/INCLUDE/DSP2833x_EPwm.h
MAIN/mian.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/LED_sample_test/INCLUDE/DSP2833x_EQep.h
MAIN/mian.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/LED_sample_test/INCLUDE/DSP2833x_Gpio.h
MAIN/mian.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/LED_sample_test/INCLUDE/DSP2833x_I2c.h
MAIN/mian.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/LED_sample_test/INCLUDE/DSP2833x_McBSP.h
MAIN/mian.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/LED_sample_test/INCLUDE/DSP2833x_PieCtrl.h
MAIN/mian.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/LED_sample_test/INCLUDE/DSP2833x_PieVect.h
MAIN/mian.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/LED_sample_test/INCLUDE/DSP2833x_Spi.h
MAIN/mian.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/LED_sample_test/INCLUDE/DSP2833x_Sci.h
MAIN/mian.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/LED_sample_test/INCLUDE/DSP2833x_SysCtrl.h
MAIN/mian.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/LED_sample_test/INCLUDE/DSP2833x_XIntrupt.h
MAIN/mian.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/LED_sample_test/INCLUDE/DSP2833x_Xintf.h
MAIN/mian.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/LED_sample_test/INCLUDE/ext_intf.h
MAIN/mian.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/LED_sample_test/INCLUDE/DSP2833x_Examples.h
MAIN/mian.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/LED_sample_test/INCLUDE/DSP2833x_GlobalPrototypes.h
MAIN/mian.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/LED_sample_test/INCLUDE/DSP2833x_ePwm_defines.h
MAIN/mian.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/LED_sample_test/INCLUDE/DSP2833x_Dma_defines.h
MAIN/mian.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/LED_sample_test/INCLUDE/DSP2833x_I2C_defines.h
MAIN/mian.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/LED_sample_test/INCLUDE/DSP2833x_DefaultISR.h
MAIN/mian.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/LED_sample_test/ARL/LED.h
MAIN/mian.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/LED_sample_test/INCLUDE/std_int.h
