# FIXED
A_MAIN/main.obj: ../A_MAIN/main.c
A_MAIN/main.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/4_NEW_Data_Process/INCLUDE/DSP2833x_Device.h
A_MAIN/main.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/4_NEW_Data_Process/INCLUDE/DSP2833x_Adc.h
A_MAIN/main.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/4_NEW_Data_Process/INCLUDE/DSP2833x_DevEmu.h
A_MAIN/main.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/4_NEW_Data_Process/INCLUDE/DSP2833x_CpuTimers.h
A_MAIN/main.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/4_NEW_Data_Process/INCLUDE/DSP2833x_ECan.h
A_MAIN/main.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/4_NEW_Data_Process/INCLUDE/DSP2833x_ECap.h
A_MAIN/main.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/4_NEW_Data_Process/INCLUDE/DSP2833x_DMA.h
A_MAIN/main.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/4_NEW_Data_Process/INCLUDE/DSP2833x_EPwm.h
A_MAIN/main.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/4_NEW_Data_Process/INCLUDE/DSP2833x_EQep.h
A_MAIN/main.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/4_NEW_Data_Process/INCLUDE/DSP2833x_Gpio.h
A_MAIN/main.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/4_NEW_Data_Process/INCLUDE/DSP2833x_I2c.h
A_MAIN/main.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/4_NEW_Data_Process/INCLUDE/DSP2833x_McBSP.h
A_MAIN/main.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/4_NEW_Data_Process/INCLUDE/DSP2833x_PieCtrl.h
A_MAIN/main.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/4_NEW_Data_Process/INCLUDE/DSP2833x_PieVect.h
A_MAIN/main.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/4_NEW_Data_Process/INCLUDE/DSP2833x_Spi.h
A_MAIN/main.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/4_NEW_Data_Process/INCLUDE/DSP2833x_Sci.h
A_MAIN/main.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/4_NEW_Data_Process/INCLUDE/DSP2833x_SysCtrl.h
A_MAIN/main.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/4_NEW_Data_Process/INCLUDE/DSP2833x_XIntrupt.h
A_MAIN/main.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/4_NEW_Data_Process/INCLUDE/DSP2833x_Xintf.h
A_MAIN/main.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/4_NEW_Data_Process/INCLUDE/DSP2833x_Examples.h
A_MAIN/main.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/4_NEW_Data_Process/INCLUDE/DSP2833x_GlobalPrototypes.h
A_MAIN/main.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/4_NEW_Data_Process/INCLUDE/DSP2833x_ePwm_defines.h
A_MAIN/main.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/4_NEW_Data_Process/INCLUDE/DSP2833x_Dma_defines.h
A_MAIN/main.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/4_NEW_Data_Process/INCLUDE/DSP2833x_I2C_defines.h
A_MAIN/main.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/4_NEW_Data_Process/INCLUDE/DSP2833x_DefaultISR.h
A_MAIN/main.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/4_NEW_Data_Process/4_DataPro_ARL/DATA_Process.h
A_MAIN/main.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/4_NEW_Data_Process/A_MAIN/std_init.h
A_MAIN/main.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/4_NEW_Data_Process/4_DataPro_ARL/ConstData_Table.h
A_MAIN/main.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/4_NEW_Data_Process/INCLUDE/IQmathLib.h
A_MAIN/main.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/4_NEW_Data_Process/1_AD7656_ARL/AD7656.h
A_MAIN/main.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/4_NEW_Data_Process/3_SCI_ARL/hmi_user_uart.h
A_MAIN/main.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/4_NEW_Data_Process/2_AD9833_ARL/AD9833.h
A_MAIN/main.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/4_NEW_Data_Process/5_LED_ARL/LED.h
A_MAIN/main.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/4_NEW_Data_Process/6_TempCtrl_ARL/DS18B20.h
A_MAIN/main.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/4_NEW_Data_Process/7_FTF_ARL/cmd_process.h
A_MAIN/main.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/4_NEW_Data_Process/7_FTF_ARL/hmi_driver.h
A_MAIN/main.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/4_NEW_Data_Process/7_FTF_ARL/cmd_queue.h
