# FIXED
3_SCI_ARL/hmi_user_uart.obj: ../3_SCI_ARL/hmi_user_uart.c
3_SCI_ARL/hmi_user_uart.obj: ../3_SCI_ARL/hmi_user_uart.h
3_SCI_ARL/hmi_user_uart.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_Device.h
3_SCI_ARL/hmi_user_uart.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_Adc.h
3_SCI_ARL/hmi_user_uart.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_DevEmu.h
3_SCI_ARL/hmi_user_uart.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_CpuTimers.h
3_SCI_ARL/hmi_user_uart.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_ECan.h
3_SCI_ARL/hmi_user_uart.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_ECap.h
3_SCI_ARL/hmi_user_uart.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_DMA.h
3_SCI_ARL/hmi_user_uart.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_EPwm.h
3_SCI_ARL/hmi_user_uart.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_EQep.h
3_SCI_ARL/hmi_user_uart.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_Gpio.h
3_SCI_ARL/hmi_user_uart.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_I2c.h
3_SCI_ARL/hmi_user_uart.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_McBSP.h
3_SCI_ARL/hmi_user_uart.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_PieCtrl.h
3_SCI_ARL/hmi_user_uart.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_PieVect.h
3_SCI_ARL/hmi_user_uart.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_Spi.h
3_SCI_ARL/hmi_user_uart.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_Sci.h
3_SCI_ARL/hmi_user_uart.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_SysCtrl.h
3_SCI_ARL/hmi_user_uart.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_XIntrupt.h
3_SCI_ARL/hmi_user_uart.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_Xintf.h
3_SCI_ARL/hmi_user_uart.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_Examples.h
3_SCI_ARL/hmi_user_uart.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_GlobalPrototypes.h
3_SCI_ARL/hmi_user_uart.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_ePwm_defines.h
3_SCI_ARL/hmi_user_uart.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_Dma_defines.h
3_SCI_ARL/hmi_user_uart.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_I2C_defines.h
3_SCI_ARL/hmi_user_uart.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_DefaultISR.h
