# FIXED
5_LED_ARL/LED.obj: ../5_LED_ARL/LED.C
5_LED_ARL/LED.obj: ../5_LED_ARL/LED.h
5_LED_ARL/LED.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_Device.h
5_LED_ARL/LED.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_Adc.h
5_LED_ARL/LED.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_DevEmu.h
5_LED_ARL/LED.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_CpuTimers.h
5_LED_ARL/LED.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_ECan.h
5_LED_ARL/LED.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_ECap.h
5_LED_ARL/LED.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_DMA.h
5_LED_ARL/LED.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_EPwm.h
5_LED_ARL/LED.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_EQep.h
5_LED_ARL/LED.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_Gpio.h
5_LED_ARL/LED.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_I2c.h
5_LED_ARL/LED.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_McBSP.h
5_LED_ARL/LED.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_PieCtrl.h
5_LED_ARL/LED.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_PieVect.h
5_LED_ARL/LED.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_Spi.h
5_LED_ARL/LED.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_Sci.h
5_LED_ARL/LED.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_SysCtrl.h
5_LED_ARL/LED.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_XIntrupt.h
5_LED_ARL/LED.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_Xintf.h
5_LED_ARL/LED.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_Examples.h
5_LED_ARL/LED.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_GlobalPrototypes.h
5_LED_ARL/LED.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_ePwm_defines.h
5_LED_ARL/LED.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_Dma_defines.h
5_LED_ARL/LED.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_I2C_defines.h
5_LED_ARL/LED.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/INCLUDE/DSP2833x_DefaultISR.h
5_LED_ARL/LED.obj: E:/01_Master_project/Water_Detection_Project/04_Software_Design/2_NEW_Data_Process/A_MAIN/std_init.h
