# FIXED
ARL/PWM_LED.obj: ../ARL/PWM_LED.C
ARL/PWM_LED.obj: C:/workspace/LED_test/INCLUDE/DSP2833x_Device.h
ARL/PWM_LED.obj: C:/workspace/LED_test/INCLUDE/DSP2833x_Adc.h
ARL/PWM_LED.obj: C:/workspace/LED_test/INCLUDE/DSP2833x_DevEmu.h
ARL/PWM_LED.obj: C:/workspace/LED_test/INCLUDE/DSP2833x_CpuTimers.h
ARL/PWM_LED.obj: C:/workspace/LED_test/INCLUDE/DSP2833x_ECan.h
ARL/PWM_LED.obj: C:/workspace/LED_test/INCLUDE/DSP2833x_ECap.h
ARL/PWM_LED.obj: C:/workspace/LED_test/INCLUDE/DSP2833x_DMA.h
ARL/PWM_LED.obj: C:/workspace/LED_test/INCLUDE/DSP2833x_EPwm.h
ARL/PWM_LED.obj: C:/workspace/LED_test/INCLUDE/DSP2833x_EQep.h
ARL/PWM_LED.obj: C:/workspace/LED_test/INCLUDE/DSP2833x_Gpio.h
ARL/PWM_LED.obj: C:/workspace/LED_test/INCLUDE/DSP2833x_I2c.h
ARL/PWM_LED.obj: C:/workspace/LED_test/INCLUDE/DSP2833x_McBSP.h
ARL/PWM_LED.obj: C:/workspace/LED_test/INCLUDE/DSP2833x_PieCtrl.h
ARL/PWM_LED.obj: C:/workspace/LED_test/INCLUDE/DSP2833x_PieVect.h
ARL/PWM_LED.obj: C:/workspace/LED_test/INCLUDE/DSP2833x_Spi.h
ARL/PWM_LED.obj: C:/workspace/LED_test/INCLUDE/DSP2833x_Sci.h
ARL/PWM_LED.obj: C:/workspace/LED_test/INCLUDE/DSP2833x_SysCtrl.h
ARL/PWM_LED.obj: C:/workspace/LED_test/INCLUDE/DSP2833x_XIntrupt.h
ARL/PWM_LED.obj: C:/workspace/LED_test/INCLUDE/DSP2833x_Xintf.h
ARL/PWM_LED.obj: C:/workspace/LED_test/INCLUDE/ext_intf.h
ARL/PWM_LED.obj: C:/workspace/LED_test/INCLUDE/DSP2833x_Examples.h
ARL/PWM_LED.obj: C:/workspace/LED_test/INCLUDE/DSP2833x_GlobalPrototypes.h
ARL/PWM_LED.obj: C:/workspace/LED_test/INCLUDE/DSP2833x_ePwm_defines.h
ARL/PWM_LED.obj: C:/workspace/LED_test/INCLUDE/DSP2833x_Dma_defines.h
ARL/PWM_LED.obj: C:/workspace/LED_test/INCLUDE/DSP2833x_I2C_defines.h
ARL/PWM_LED.obj: C:/workspace/LED_test/INCLUDE/DSP2833x_DefaultISR.h
ARL/PWM_LED.obj: ../ARL/PWM_LED.h
ARL/PWM_LED.obj: ../ARL/std_int.h
